### ISSUE TITLE
React and ReactNative APIs are separated since RN 0.25

### ISSUE THREAD

**Issue by drapanjanas** [dmotz/natal-shell#1]
Hi! As noted in [RN 0.25 release notes](https://github.com/facebook/react-native/releases/tag/v0.25.1) the proper way to access React API is to `require('react')`. Access of React API via `require('react-native')` is now deprecated and will be removed in 0.26. 

To support this, natal-shell (v0.3.0) could expect both global variables defined and use for corresponsing API:

``` clojure
(set! js/window.React (js/require "react"))
(set! js/window.ReactNative (js/require "react-native"))
```

I think this can be done by changing variable names in `scraper.clj` and `components.clj`, and running the scraper. I could submit this PR if noone has better solution for this.

**Comment by dmotz** [comment]
Closed by https://github.com/dmotz/natal-shell/pull/2
