### ISSUE TITLE
reduce dependencies

### ISSUE THREAD

**Issue by carocad** [dmotz/natal-shell#5]
Hi @dmotz 
thanks a lot for taking the time to create such a library :)

I am thinking of using it (I havent so far) but after a quick look at the dependencies I noticed that you include both core.async and enlive which themselves pull a lot of other things. After a quick code search I couldnt find code calls inside the `src/` folder, which is what I think the only thing exported as part of the library.

If I understand your code right, the `script` part is run on development time and the `src` is what is actually used. If that is so then both core.async and enlive could simply be declared as `dev` dependencies, thus reducing the amount of code that this library requires

Let me know your thoughts about it :)

**Comment by dmotz** [comment]
You're right! I will update this soon.

**Comment by carocad** [comment]
thanks :)
